version: '3.8'

services:
  # Serviço da Base de Dados
  mongo_db:
    image: mongo:latest
    container_name: tomar_mongo
    ports:
      - "27017:27017" # Abre a porta para o teu PC aceder
    volumes:
      - mongo_data:/data/db # Isto garante que os dados não somem se desligares o PC!

volumes:
  mongo_data: